apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-demo
  name: flask-demo
  namespace: opentelemetry
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flask-demo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
  namespace: opentelemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-demo
  template:
    metadata:
      labels:
        app: flask-demo
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      containers:
      - name: flask-demo
        image: sonerdm/opentelemetry-flask-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
